/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export type paths = Record<string, any>;

export type webhooks = Record<string, any>;

export interface components {
  schemas: any;
  responses: any;
  parameters: any;
  requestBodies: any;
  headers: any;
  pathItems: any;
}

export type $defs = Record<string, any>;

export type external = Record<string, any>;

export type operations = Record<string, any>;
